### ISSUE TITLE
Getting exception and disconnect.

### ISSUE THREAD

**Issue by belarusrulez** [polygon-io/client-jvm#7] opened 2020-07-09 17:39 UTC
Today got this exception 3 times during connection with websocket api. Client just dies silently. Can't catch this because it's inside framework.

`Exception in thread "DefaultDispatcher-worker-7" java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:201)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:210)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
	at java.base/java.lang.Thread.run(Thread.java:832)`

**Comment by belarusrulez** [comment] 2020-07-10 02:17
I understand that it's okhttp3 issue. 
It would be nice to have possibility to add interceptor in constructor or builder to make restart work around at least. 
https://futurestud.io/tutorials/retrofit-2-catch-server-errors-globally-with-response-interceptor
while they are fixing this.

**Comment by mmoghaddam385** [comment] 2020-07-10 14:05
Hi @belarusrulez, is this exception making it to the websocket listener's `onError` callback? 

There is a way to provide your own `HttpClientProvider` when constructing your websocket client. Your provider can extend `DefaultJvmHttpClientProvider` and override the `buildClient` function to return a custom ktor http client. Your custom client can have OkHttp interceptors or use a completely different engine like Apache. More details on Ktor client engines here: https://ktor.io/clients/http-client/engines.html. Just take a look at the default implementation of `buildClient` to see what features are required to be installed in the engine.

Ktor can be a bit awkward to work with, so let me know if you have more questions. In the meantime I'll look into making it simple to add OkHttp interceptors to the `DefaultJvmHttpClientProvider`

**Comment by belarusrulez** [comment] 2020-07-13 23:35
Thank you for response. Ill try this :)

**Comment by belarusrulez** [comment] 2020-07-14 16:13
Hello @mmoghaddam385  could you please rebuild it so Ill be able to use this https://github.com/polygon-io/client-jvm/blob/046cb1a3d653a0e0fd6936242d502b78692f052b/src/main/kotlin/io/polygon/kotlin/sdk/HttpClientProvider.kt changes?

Thank you :)

**Comment by mmoghaddam385** [comment] 2020-07-14 16:17
Oops, forgot to create a new release! Just created 1.1.0, should be good to go!

**Comment by belarusrulez** [comment] 2020-07-14 19:45
Hello, Thank you for quick response :)

I've tried to catch this exception .... like this:

![image](https://user-images.githubusercontent.com/1071191/87469190-bee80400-c5cf-11ea-8251-5a25146d0b14.png)

looks like it never comes here :D still getting the same stacktrace and disconnect.

**Comment by mmoghaddam385** [comment] 2020-07-15 13:53
I was afraid that might happen, it doesn't seem like OkHttp interceptors really do all that much in websocket connections. At this point I'd suggest dropping OkHttp and trying out a different engine. The CIO engine (https://ktor.io/clients/http-client/engines.html#cio) support websockets and should be a drop-in replacement for OkHttp. 

See [the sample code](https://github.com/polygon-io/client-jvm/blob/046cb1a3d653a0e0fd6936242d502b78692f052b/sample/src/main/java/io/polygon/kotlin/sdk/sample/KotlinUsageSample.kt#L48) for an example of how to swap out your http engine. (you'll also need to include the dependency from the ktor.io link above)

Let me know if you have any better luck with CIO, if you do I'll think about making that the default instead of OkHttp for now

**Comment by mmoghaddam385** [comment] 2021-01-05 15:08
Hi @belarusrulez, are you still having this issue?

**Comment by mmoghaddam385** [comment] 2021-06-09 15:08
I'm going to close this because I think the disconnects were being caused by a server-side issue at the time which has since been fixed. Feel free to re-open if I'm wrong though!

**Closed by mmoghaddam385** 2021-06-09 15:08 UTC
